name: Build Project

env:
  PROJECT: canary-driver
  AUTHOR: calladoum-elastic
  VERBOSE: 1

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  Build:
    name: "Building ${{ matrix.os }}/${{ matrix.platform }}/${{ matrix.configuration }}"
    env:
     CMAKE_FLAGS: "-DDEBUG=ON"
     NB_CPU: 1

    strategy:
      fail-fast: false
      matrix:
        os: ['windows-2022']
        platform: ['x64', 'win32', 'arm64']
        configuration: ['RelWithDebInfo']

    runs-on: ${{ matrix.os }}
    permissions:
      actions: read
      contents: read

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Prepare
      shell: pwsh
      run: |
        echo NB_CPU=$env:NUMBER_OF_PROCESSORS | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
        Import-Module .\.github\Invoke-VisualStudio.ps1
        Invoke-VisualStudio2022${{ matrix.platform }}

    - name: Compile
      run: |
        mkdir build
        cmake -S . -B ./build -A ${{ matrix.platform }} ${{ env.CMAKE_FLAGS }}
        cmake --build ./build --verbose --parallel ${{ env.NB_CPU }} --config ${{ matrix.configuration }}

    - name: Install
      run: |
        mkdir artifact
        cmake --install ./build --config ${{ matrix.configuration }} --prefix ./artifact --verbose

    - name: Publish
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.PROJECT }}_${{ matrix.os }}_${{ matrix.platform }}_${{ github.sha }}
        path: artifact/
